services:
  database:
    image: "postgres:16.8-alpine3.21"
    environment:
      POSTGRES_PASSWORD: "local_password"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
